[tools]
go = "1.26.5"
task = "3.52.0"
golangci-lint = "2.12.2"
tflint = "0.63.1"
trivy = "0.72.0"
bats = "1.13.0"
hadolint = "2.14.0"
jq = "1.8.2"
shellcheck = "0.11.0"
shfmt = "3.13.1"
actionlint = "1.7.12"
goreleaser = "2.17.0"
